### ISSUE TITLE
how can i use it in my iphone.

### ISSUE THREAD

**Issue by FivredSeven** [Shadowsocks-Wiki/shadowsocks#3]
i am in china. 
i can not find the app Shadowrocket and Potatso Lite in app store.  so how can i use your product.

**Comment by sssshadowsocks** [comment]
https://portal.shadowsocks.la/aff.php?aff=12091
更改一个国外的apple id 下载potatso 嗯，然后扫描自己的配置二维码就可以使用了

**Comment by Shadowsocks-Wiki** [comment]
請參考：
https://github.com/Shadowsocks-Wiki/shadowsocks/blob/master/4-ios-settings.md
